{
"records":
[
{
"filename":"/static/angularjsfile/video/雇佣兵A.mp4",
"img":"/static/angularjsfile/img/p1.jpg",
"teacher":"李强",
"outline":"概要:课程提纲",
"description":"课程简介：雇佣兵A",
"number":"215人参加学习",
"time":"38课时58分钟"
},
{
"filename":"/static/angularjsfile/video/雇佣兵B.mp4",
"img":"/static/angularjsfile/img/p2.jpg",
"teacher":"朱三中",
"outline":"概要:课程提纲",
"description":"课程简介：雇佣兵B",
"number":"437人参加学习",
"time":"133课时58分钟"
},
{
"filename":"/static/angularjsfile/video/美女杠铃.mp4",
"img":"/static/angularjsfile/img/p3.jpg",
"teacher":"王天光",
"outline":"概要:课程提纲",
"description":"课程简介：美女杠铃",
"number":"271人参加学习",
"time":"12课时58分钟"
},
{
"filename":"/static/angularjsfile/video/闻香识女人B.mp4",
"img":"/static/angularjsfile/img/p4.jpg",
"teacher":"悟空",
"outline":"概要:课程提纲",
"description":"课程简介：闻香识女人B",
"number":"236人参加学习",
"time":"31课时58分钟"
}
]
}