{
"records":
[
{
"id":"0",
"numbering":"1",
"filename":"/static/angularjsfile/video/cctv12/雇佣兵A.mp4",
"description":"介绍雇佣兵A。",
"time":"28",
"number":"75",
"date":"2016.3.5"
},
{
"id":"0",
"numbering":"2",
"filename":"/static/angularjsfile/video/cctv12/雇佣兵B.mp4",
"description":"介绍雇佣兵B。",
"time":"38",
"number":"552",
"date":"2016.3.26"
},
{
"id":"0",
"numbering":"3",
"filename":"/static/angularjsfile/video/cctv12/美女杠铃.mp4",
"description":"介绍美女杠铃。",
"time":"38",
"number":"961",
"date":"2016.3.08"
},
{
"id":"0",
"numbering":"4",
"filename":"/static/angularjsfile/video/cctv12/闻香识女人A.mp4",
"description":"介绍闻香识女人A。",
"time":"67",
"number":"96",
"date":"2016.3.16"
},
{
"id":"1",
"numbering":"1",
"filename":"/static/angularjsfile/video/python/Flask操作数据库.mp4",
"description":"介绍python Flask操作数据库。",
"time":"128",
"number":"175",
"date":"2016.3.20"
},
{
"id":"1",
"numbering":"2",
"filename":"/static/angularjsfile/video/python/Flask与BootStrap搭建网页.mp4",
"description":"介绍python Flask与BootStrap搭建网页。",
"time":"78",
"number":"65",
"date":"2016.3.25"
},
{
"id":"1",
"numbering":"3",
"filename":"/static/angularjsfile/video/python/Flask与数据库.mp4",
"description":"介绍python Flask与数据库。",
"time":"338",
"number":"196",
"date":"2016.3.11"
},
{
"id":"1",
"numbering":"4",
"filename":"/static/angularjsfile/video/python/在Flask中使用MySQL.mp4",
"description":"介绍python 在Flask中使用MySQL。",
"time":"78",
"number":"278",
"date":"2016.5.12"
},
{
"id":"1",
"numbering":"5",
"filename":"/static/angularjsfile/video/python/增加的内容在Flask中使用MySQL.mp4",
"description":"增加的内容介绍python 在Flask中使用MySQL。",
"time":"178",
"number":"306",
"date":"2016.5.12"
}
]
}